import{G as h,c as u,g as l,B as f,a as m}from"./assets/gallery-pagination-58072343.js";/* empty css                      */import{i as b,S as d}from"./assets/vendor-9310f15c.js";const n="/goit-js-homework-12/assets/icons-5e8cbe24.svg",p="/goit-js-homework-12/assets/bi-x-octagon-73f29380.svg";function y(e){b.show({message:e,messageColor:"#fafafb",messageSize:"16px",backgroundColor:"#fc5a5a",position:"topRight",closeOnEscape:!0,close:!0,icon:"Icomoon",iconUrl:`${p}`,iconColor:"#fafafb"})}const s=document.querySelector(".gallery"),c=document.querySelector(".border-loader"),i=document.querySelector(".search-form");i.addEventListener("submit",v);let a="";const g=20;let r=new d(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,nav:!0,navText:[`<svg class="lightbox-button-icon-prev" width="24" height="24" aria-label="icon arrow left">
          <use href="${n}#icon-chevron-left"></use>
        </svg>`,`<svg class="lightbox-button-icon-next" width="24" height="24" aria-label="icon arrow right">
          <use href="${n}#icon-chevron-right"></use>
        </svg>`],close:!0,closeText:`
        <svg class="lightbox-close-icon" width="16" height="16">
          <use href="${n}#close-form"></use>
        </svg>`,enableKeyboard:!0,showCounter:!0,animationSlide:!0,loop:!0});const t=new h({data:[],fnCreateMarkup:u,fnGetImages:l,contentRef:s,elementsPerPage:g,searchStr:a,boxRef:r});function v(e){e.preventDefault(),c.style.display="block",a=e.currentTarget.search.value.trim(),l(a,1).then(o=>w(o)).catch(o=>x(o))}function x(e){i.search.value="",c.style.display="none",y(e),s.style.backgroundColor=f,s.innerHTML="",t&&t.refresh(),r&&r.refresh()}function w(e){i.search.value="",c.style.display="none",s.style.backgroundColor=m,t&&t.refresh();const o=Math.ceil(e.totalHits/g);t.addData(e.hits,o,a),r&&r.refresh()}
//# sourceMappingURL=commonHelpers2.js.map
